extract build progress from Ninja script output
colcon/colcon-notification pull request #62
Opened 2022-12-10 22:10 UTC by christianrauch

This extends the parsing of make stdout to get the build progress in the form of [XXX%] with parsing of Ninja stdout in the form of [X/Y]. Here, X and Y can be arbitrary large numbers with X<=Y, which is converted to a percentage.

2022-12-11 00:28 UTC, christianrauch commented
Not sure what the issue with the patch on the CI is, but this was probably introduced with https://github.com/colcon/colcon-notification/pull/61. This PR should be unrelated to this CI error, since it does not touch the patched file. Running `python3 setup.py --command-packages=stdeb.command bdist_deb` manually on my system (Ubuntu 22.04) creates the deb successfully without the `.app` folder.

2022-12-14 00:56 UTC, cottsay commented
> Not sure what the issue with the patch on the CI is

It's colcon/ci#10

2022-12-14 18:25 UTC, christianrauch commented
> > Not sure what the issue with the patch on the CI is
> 
> It's [colcon/ci#10](https://github.com/colcon/ci/pull/10)

Is there a fix for that? I see that the [`master`](https://github.com/colcon/colcon-notification/commits/master) branch has the same problem but this only appeared with the [most recent commit](https://github.com/colcon/colcon-notification/commit/8ae243584c7efd8d2912057d3911a6e156afcece).

Locally, this still seems to work and it is just an issue with the CI. Can we merge this nevertheless, given that the problem already exists on master, or is there going to be a fix on top of which I have to rebase my PR?

2022-12-14 22:59 UTC, cottsay commented
> Is there a fix for that?

That was the fix. It's merged now and I recovered both the `master` CI and this PR build.

2022-12-14 23:14 UTC, christianrauch commented
> > Is there a fix for that?
> 
> That was the fix. It's merged now and I recovered both the `master` CI and this PR build.

Sorry, I overlooked that this is in another repo. Thanks for fixing the CI.

Now that the CI passes, can you also review my PR? :smiley:

2022-12-14 23:45 UTC, cottsay requested changes

2022-12-14 23:45 UTC, cottsay commented on colcon_notification/event_handler/status.py
> +        self._progress_pattern_ninja = re.compile(r'^\[([0-9]+)\/([0-9]+)\] ')
Can we generalize these variables? Maybe `_progress_pattern_percent` and `_progress_pattern_steps`? If/when we extend this for other tools we'll be able to simply update the existing patterns.

2022-12-14 23:45 UTC, cottsay commented on colcon_notification/event_handler/status.py
> +            if not match_make and not match_ninja:
I'd like to see this take a "first match wins" approach to avoid running `.match()` when we won't care.

2022-12-14 23:45 UTC, cottsay commented on colcon_notification/event_handler/status.py
> +                    int(match_ninja.group(1))/int(match_ninja.group(2))))
In the presence of both patterns (unlikely, but still), we should prefer the existing/more common pattern used by GNU make, which is not how this code will behave. Unless there is a specific reason to do the opposite, of course.

2022-12-15 18:51 UTC, christianrauch commented
Thanks for the review. I renamed the variables and changed the if/else conditions so that the "percentage" matching takes precedence and "fraction" matching is skipped if a "percentage" match has already been found.

2022-12-16 23:53 UTC, cottsay approved these changes
Thanks for your contribution.

I took the liberty of adding some simple tests here. Please take a look and tweak them as you see fit, and give me an @mention when you're satisfied.

2022-12-17 00:25 UTC, christianrauch commented
> I took the liberty of adding some simple tests here. Please take a look and tweak them as you see fit, and give me an @mention when you're satisfied.

@cottsay Thanks for adding the test. I played around with it a bit to make the test fail. It seems to behave as expected.

2022-12-17 00:28 UTC, merged